#!/usr/bin/env python3
#
# Generate CFFI-friendly declarations for Penguin's QEMU embedding ABI.

import argparse
import json
import tarfile
from pathlib import Path


SYSTEM_TARGETS = {
    "intel64": "x86_64-softmmu",
    "x86_64": "x86_64-softmmu",
    "armel": "arm-softmmu",
    "arm": "arm-softmmu",
    "aarch64": "aarch64-softmmu",
    "mipsel": "mipsel-softmmu",
    "mipseb": "mips-softmmu",
    "mips": "mips-softmmu",
    "mips64el": "mips64el-softmmu",
    "mips64eb": "mips64-softmmu",
    "mips64": "mips64-softmmu",
    "powerpc": "ppc-softmmu",
    "ppc": "ppc-softmmu",
    "powerpc64": "ppc64-softmmu",
    "powerpc64le": "ppc64-softmmu",
    "powerpc64el": "ppc64-softmmu",
    "ppc64": "ppc64-softmmu",
    "riscv64": "riscv64-softmmu",
    "loongarch64": "loongarch64-softmmu",
}

VADDR_BITS = {
    "armel": 32,
    "arm": 32,
    "mipsel": 32,
    "mipseb": 32,
    "mips": 32,
    "powerpc": 32,
    "ppc": 32,
}


HEADER_TEMPLATE = """\
/*
 * Generated by scripts/penguin-cffi-gen.py.
 *
 * These declarations are intentionally limited to Penguin's stable QEMU
 * embedding ABI and are suitable for:
 *
 *     ffi = cffi.FFI()
 *     ffi.cdef(open(header_path).read())
 *     lib = ffi.dlopen(library_path)
 */

typedef _Bool bool;
typedef {vaddr_type} vaddr;

typedef struct CPUState CPUState;
typedef struct MachineState MachineState;
typedef struct MemoryRegion MemoryRegion;
typedef struct AddressSpace AddressSpace;

typedef int (*penguin_guest_hypercall_cb_t)(CPUState *cs, uint64_t nr,
                                            uint64_t a0, uint64_t a1,
                                            uint64_t a2, uint64_t a3,
                                            uint64_t a4, uint64_t a5,
                                            uint64_t *ret, void *opaque);

typedef int (*kvm_penguin_hypercall_cb_t)(CPUState *cs, uint64_t nr,
                                          uint64_t a0, uint64_t a1,
                                          uint64_t a2, uint64_t a3,
                                          uint64_t a4, uint64_t a5,
                                          uint64_t *ret);

typedef int (*kvm_penguin_after_guest_init_cb_t)(MachineState *machine,
                                                 void *opaque);
typedef uint64_t (*penguin_mmio_read_cb_t)(uint64_t addr, unsigned size,
                                           void *opaque);
typedef void (*penguin_mmio_write_cb_t)(uint64_t addr, uint64_t data,
                                        unsigned size, void *opaque);

typedef void (*penguin_reset_request_cb_t)(int reason, void *opaque);
typedef bool (*penguin_qmp_cb_t)(const char *command, const char *args,
                                 char **result, void *opaque);

extern MachineState *current_machine;
extern int (*qemu_main)(void);

int main(int argc, char **argv);
void qemu_init(int argc, char **argv);
int qemu_main_loop(void);
void qemu_cleanup(int status);
void qemu_system_shutdown_request(int reason);
void bql_lock_impl(const char *file, int line);
void bql_unlock(void);
void replay_mutex_lock(void);
void replay_mutex_unlock(void);
bool bql_locked(void);
bool replay_mutex_locked(void);

CPUState *qemu_get_cpu(int index);
int cpu_memory_rw_debug(CPUState *cpu, vaddr addr, void *ptr, size_t len,
                        bool is_write);

void set_penguin_guest_hypercall_callback(penguin_guest_hypercall_cb_t cb,
                                          void *opaque);
void penguin_register_guest_hypercall(uint64_t nr);
void penguin_unregister_guest_hypercall(uint64_t nr);
void penguin_clear_guest_hypercalls(void);
bool penguin_guest_hypercall_registered(uint64_t nr);
void set_kvm_penguin_hypercall_callback(kvm_penguin_hypercall_cb_t cb);
void set_kvm_penguin_after_guest_init_callback(
    kvm_penguin_after_guest_init_cb_t cb, void *opaque);

bool penguin_handle_guest_hypercall(CPUState *cs, uint64_t nr,
                                    uint64_t a0, uint64_t a1,
                                    uint64_t a2, uint64_t a3,
                                    uint64_t a4, uint64_t a5,
                                    uint64_t *ret);
int penguin_qemu_add_mmio_region(uint64_t base, uint64_t size,
                                 const char *name,
                                 penguin_mmio_read_cb_t read_cb,
                                 penguin_mmio_write_cb_t write_cb,
                                 void *opaque);
int penguin_read_guest_reg(CPUState *cs, int regnum, uint8_t *buf,
                           int buf_len);
int penguin_write_guest_reg(CPUState *cs, int regnum, const uint8_t *buf,
                            int len);
void *penguin_cpu_env(CPUState *cs);
void penguin_sync_cpu_state(CPUState *cs);
bool penguin_save_snapshot(const char *name);
bool penguin_load_snapshot(const char *name);
void penguin_schedule_snapshot(const char *name, bool load);
void set_penguin_reset_request_callback(penguin_reset_request_cb_t cb, void *opaque);
void set_penguin_qmp_callback(penguin_qmp_cb_t cb, void *opaque);
bool penguin_handle_qmp(const char *command, const char *args, char **result);
"""


def split_csv(value):
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def vaddr_bits_for_arch(arch):
    return VADDR_BITS.get(arch, 64)


def system_entries(arches):
    for arch in split_csv(arches):
        try:
            qemu_target = SYSTEM_TARGETS[arch]
        except KeyError as exc:
            raise SystemExit(f"unsupported Penguin system arch: {arch}") from exc

        yield {
            "arch": arch,
            "qemu_target": qemu_target,
            "library": f"libqemu-system-{arch}.so",
            "header": f"qemu_cffi_system_{arch}.h",
            "vaddr_bits": vaddr_bits_for_arch(arch),
        }


def kvm_entries(targets):
    for target in split_csv(targets):
        if not target.endswith("-softmmu"):
            raise SystemExit(f"unsupported KVM target: {target}")
        arch = target.removesuffix("-softmmu")
        yield {
            "arch": arch,
            "qemu_target": target,
            "library": f"libqemu-kvm-{arch}.so",
            "header": f"qemu_cffi_kvm_{arch}.h",
            "vaddr_bits": vaddr_bits_for_arch(arch),
        }


def write_header(build_dir, entry):
    vaddr_type = "uint32_t" if entry["vaddr_bits"] == 32 else "uint64_t"
    path = build_dir / entry["header"]
    path.write_text(HEADER_TEMPLATE.format(vaddr_type=vaddr_type))
    return path


def write_package(build_dir, mode, files):
    package = build_dir / f"penguin-qemu-cffi-{mode}.tar.gz"
    with tarfile.open(package, "w:gz") as archive:
        for path in files:
            archive.add(path, arcname=path.name)
    return package


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("system", "kvm"), required=True)
    parser.add_argument("--build-dir", required=True)
    parser.add_argument("--arches", default="")
    parser.add_argument("--targets", default="")
    args = parser.parse_args()

    build_dir = Path(args.build_dir)
    build_dir.mkdir(parents=True, exist_ok=True)

    if args.mode == "system":
        entries = list(system_entries(args.arches))
    else:
        entries = list(kvm_entries(args.targets))

    files = []
    for entry in entries:
        library_path = build_dir / entry["library"]
        if not library_path.exists():
            raise SystemExit(f"missing built library: {library_path}")
        files.append(write_header(build_dir, entry))

    manifest = {
        "schema": 1,
        "mode": args.mode,
        "headers": entries,
    }
    manifest_path = build_dir / f"qemu_cffi_{args.mode}_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    files.append(manifest_path)

    package = write_package(build_dir, args.mode, files)
    print(f"Wrote {len(entries)} CFFI headers and {package}")


if __name__ == "__main__":
    main()
